In [2]:
print("Hello world1!")

Hello world1!


In [3]:
import numpy as np
# remember to run this and then code

In [4]:
# Basic array in numpy (array of ints)
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [5]:
b = np.array([[9.0, 2.0, 3.0], [7.0, 6.0, 5.0]])
b

array([[9., 2., 3.],
       [7., 6., 5.]])

In [6]:
# get dimension
# a.ndim
b.ndim

2

In [7]:
# get shape
b.shape

(2, 3)

In [8]:

# size of array and type
a.dtype 

# default (int64)
# can be set using dtype argument during init
a.itemsize
a.itemsize * a.size == a.nbytes 


b.itemsize
b.dtype == 'double' # float64 == double

True

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
# Get a specific element
a[1, 5]
a[-1, -1]

14

In [11]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get specific coloumn
a[:, 2]

array([ 3, 10])

In [13]:
# Self explanatory
# a[r, startInd: endInd: stepSize]
a[0, 1:-2:2]
a[1, 5] = 8
a[-1, -1] = 13
# Also numpy array changes are global
a[:, 2] = [3, 10]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12,  8, 13]])

In [14]:
""" 3D Arrays """

b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
b[1, :, :] = [[8, 8], [13, 13]]
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 8,  8],
        [13, 13]]])

In [16]:
# All zeros matrix

a = np.zeros((2, 2), dtype='int')
a.dtype


dtype('int64')

In [17]:
# All ones
a = np.ones((2, 3), dtype='int')
a

np.full((4, 3), 6)
np.full_like(a, 5) # Not a.shape -> send a as arg
np.full(a.shape, 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [18]:
np.random.rand(2, 3) # inits an array with given args as row and col lengths elements between (0, 1)
np.random.random_sample(a.shape)
# np.random.random_integers(a.shape[0], a.shape[1]) -> dont use


np.random.randint(6, size = (2, 3)) # One we need

array([[4, 1, 2],
       [1, 5, 1]])

In [19]:
# Identity matrix
I = np.identity(3, dtype='int')
I.shape

(3, 3)

In [20]:
# Repeat an array
arr = np.array([1, 2, 3])
r = np.repeat(arr, 3)
r

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [21]:
output = np.ones((5, 5), dtype='int')

zeros = np.zeros((3, 3), dtype='int')
zeros[1, 1] = 9

output[1:4, 1:4, ] = zeros
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

##### Be careful when copying arrays!!! 

In [22]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [23]:
# Shallow copy (dangerous)
b = a
b[1] = 6
a

c = a.copy()
c[1] = 11
print(a, c)

[1 6 3] [ 1 11  3]


##### Mathematics

In [25]:
''' Mathematics in numpy '''
a = np.array([1, 2, 3, 4])
a, a + 2, a - 2

(array([1, 2, 3, 4]), array([3, 4, 5, 6]), array([-1,  0,  1,  2]))

In [ ]:
a + 2 # Add 2 to each element
a - 2 # Sub 2 from each element

In [27]:
a * 2, a // 2

(array([2, 4, 6, 8]), array([0, 1, 1, 2]))

In [29]:
a += 2 # Also supported
a

array([5, 6, 7, 8])

In [30]:
b = np.array([1, 0, 1, 0])
a + b

array([6, 6, 8, 8])

In [31]:
# Sine of all values
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

##### Linear Algebra

In [33]:
a = np.ones((2, 3), dtype = 'long')
a

b = np.full((3, 2), 2)
b


array([[2, 2],
       [2, 2],
       [2, 2]])

In [34]:
np.matmul(a, b)

array([[6, 6],
       [6, 6]])

In [37]:
# Find determinant
c = np.identity(3)
np.linalg.det(np.matmul(a, b))
np.linalg.det(c)

1.0

##### Stats

In [42]:
stats = np.array([[1, 8, 3], [4, 5, 6]])
stats

array([[1, 8, 3],
       [4, 5, 6]])

In [43]:
np.min(stats, axis = 1)

array([1, 4])

In [45]:
# Gives the max values n-tuple along given axis 0 - x, 1 - y
np.max(stats, axis = 1)

array([8, 6])

In [46]:
np.sum(stats)

27

##### Reorganizing Arrays

In [51]:
bef = np.array([[1,2,3,4], [5,6,7,8]])
aft = bef.reshape((4, 2))

bef, aft

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [55]:
# Vertically stacking matrices
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

v3 = np.vstack([v1, v2])
v4 = v3.copy()

np.hstack([v3, v4])

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

##### Load data from file

In [69]:
filedata =  np.genfromtxt('text.txt', delimiter = ',')
filedata = filedata.astype('long')
# filedata

In [65]:
# Boolean Masking
(filedata > 25) & (filedata < 33)

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True, False, False]])

##### Boolean masking and Advanced indexing

In [70]:
filedata[filedata > 25]

array([27, 29, 31, 33, 35, 27, 29, 31, 33, 35, 27, 29, 31, 33, 35])

In [72]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

In [76]:
# Checks if the condition is correct in every column for any val
np.any(filedata > 25, axis = 0)

# Checks if the condition is correct in every column for all vals  
np.all(filedata > 25, axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True])

In [77]:
# Checks if condition is correct in every row for any val
np.any(filedata > 25, axis = 1)

array([ True,  True,  True])